//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msdev.kirodk.Resources.Views.Admin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardController_IndexNavText {
            get {
                return ResourceManager.GetString("DashboardController_IndexNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PropertyKey {
            get {
                return ResourceManager.GetString("PropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PropertyValue {
            get {
                return ResourceManager.GetString("PropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Setting.
        /// </summary>
        public static string SettingsController_CreateNavText {
            get {
                return ResourceManager.GetString("SettingsController_CreateNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsController_IndexNavText {
            get {
                return ResourceManager.GetString("SettingsController_IndexNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Endorsement.
        /// </summary>
        public static string UsersController_AddClaimNavText {
            get {
                return ResourceManager.GetString("UsersController_AddClaimNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string UsersController_AddRoleNavText {
            get {
                return ResourceManager.GetString("UsersController_AddRoleNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string UsersController_CreateNavText {
            get {
                return ResourceManager.GetString("UsersController_CreateNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attributes.
        /// </summary>
        public static string UsersController_EditUserClaimsNavText {
            get {
                return ResourceManager.GetString("UsersController_EditUserClaimsNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string UsersController_EditUserNavText {
            get {
                return ResourceManager.GetString("UsersController_EditUserNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Roles.
        /// </summary>
        public static string UsersController_EditUserRolesNavText {
            get {
                return ResourceManager.GetString("UsersController_EditUserRolesNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer Users.
        /// </summary>
        public static string UsersController_ListNavText {
            get {
                return ResourceManager.GetString("UsersController_ListNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer Endorsements.
        /// </summary>
        public static string UsersController_ViewAllClaimsNavText {
            get {
                return ResourceManager.GetString("UsersController_ViewAllClaimsNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer Roles.
        /// </summary>
        public static string UsersController_ViewAllRolesNavText {
            get {
                return ResourceManager.GetString("UsersController_ViewAllRolesNavText", resourceCulture);
            }
        }
    }
}
