//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msdev.kirodk.Resources.Views.Manage.ViewTranslation", typeof(ViewTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string AddPhoneNumberNavText {
            get {
                return ResourceManager.GetString("AddPhoneNumberNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        public static string AddPhoneNumberSubTitle {
            get {
                return ResourceManager.GetString("AddPhoneNumberSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string AddPhoneNumberTitle {
            get {
                return ResourceManager.GetString("AddPhoneNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordNavText {
            get {
                return ResourceManager.GetString("ChangePasswordNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordSubTitle {
            get {
                return ResourceManager.GetString("ChangePasswordSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string ManageIndexNavText {
            get {
                return ResourceManager.GetString("ManageIndexNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ManageIndexSubTitle {
            get {
                return ResourceManager.GetString("ManageIndexSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string ManageIndexTextExternalLogins {
            get {
                return ResourceManager.GetString("ManageIndexTextExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ManageIndexTextPassword {
            get {
                return ResourceManager.GetString("ManageIndexTextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication.
        /// </summary>
        public static string ManageIndexTextTwofactorAuth {
            get {
                return ResourceManager.GetString("ManageIndexTextTwofactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageIndexTitle {
            get {
                return ResourceManager.GetString("ManageIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Logins.
        /// </summary>
        public static string ManageLoginsNavText {
            get {
                return ResourceManager.GetString("ManageLoginsNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string ManageLoginsSubTitle {
            get {
                return ResourceManager.GetString("ManageLoginsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageLoginsTitle {
            get {
                return ResourceManager.GetString("ManageLoginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string OtherLoginsButtonTitle {
            get {
                return ResourceManager.GetString("OtherLoginsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string RemoveButtonTitle {
            get {
                return ResourceManager.GetString("RemoveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string SetPasswordInfoText {
            get {
                return ResourceManager.GetString("SetPasswordInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string SetPasswordNavText {
            get {
                return ResourceManager.GetString("SetPasswordNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string SetPasswordSubTitle {
            get {
                return ResourceManager.GetString("SetPasswordSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string SetPasswordTitle {
            get {
                return ResourceManager.GetString("SetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify PhoneNumber.
        /// </summary>
        public static string VerifyPhoneNumberNavText {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberNavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string VerifyPhoneNumberSubTitle {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumberTitle {
            get {
                return ResourceManager.GetString("VerifyPhoneNumberTitle", resourceCulture);
            }
        }
    }
}
