//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Admin.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msdev.kirodk.Resources.Views.Admin.Users.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRoleButtonText {
            get {
                return ResourceManager.GetString("AddRoleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ClaimType_Country {
            get {
                return ResourceManager.GetString("ClaimType_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string ClaimType_DateOfBirth {
            get {
                return ResourceManager.GetString("ClaimType_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ClaimType_Gender {
            get {
                return ResourceManager.GetString("ClaimType_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ClaimType_GivenName {
            get {
                return ResourceManager.GetString("ClaimType_GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string ClaimType_HomePhone {
            get {
                return ResourceManager.GetString("ClaimType_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ClaimType_Locality {
            get {
                return ResourceManager.GetString("ClaimType_Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string ClaimType_MobilePhone {
            get {
                return ResourceManager.GetString("ClaimType_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string ClaimType_PostalCode {
            get {
                return ResourceManager.GetString("ClaimType_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string ClaimType_StreetAddress {
            get {
                return ResourceManager.GetString("ClaimType_StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you want to strip user from role {0}?.
        /// </summary>
        public static string DeleteRoleConfirmationText {
            get {
                return ResourceManager.GetString("DeleteRoleConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure you want to delete the user {0}?.
        /// </summary>
        public static string DeleteUserConfirmationText {
            get {
                return ResourceManager.GetString("DeleteUserConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Roles:.
        /// </summary>
        public static string EditRolesTableHeaderText {
            get {
                return ResourceManager.GetString("EditRolesTableHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed attempts.
        /// </summary>
        public static string User_AccessFailedCount {
            get {
                return ResourceManager.GetString("User_AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout End Date .
        /// </summary>
        public static string User_LockoutEndDateUtc {
            get {
                return ResourceManager.GetString("User_LockoutEndDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string User_PhoneNumber {
            get {
                return ResourceManager.GetString("User_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsement Type.
        /// </summary>
        public static string UserClaim_ClaimType {
            get {
                return ResourceManager.GetString("UserClaim_ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsment Value.
        /// </summary>
        public static string UserClaim_ClaimValue {
            get {
                return ResourceManager.GetString("UserClaim_ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UserRoles_RoleName {
            get {
                return ResourceManager.GetString("UserRoles_RoleName", resourceCulture);
            }
        }
    }
}
